#############################################################################
# Makefile for building: gm_open
# Generated by qmake (2.01a) (Qt 4.7.1) on: Fri May 13 13:18:48 2011
# Project:  gm_open.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile gm_open.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -O3 -mfpmath=sse -msse2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -fopenmp -O2 -O3 -mfpmath=sse -msse2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtOpenGL -I/usr/include/QtXml -I/usr/include -I/usr/include -I/usr/X11R6/include -I.moc
LINK          = g++
LFLAGS        = -fopenmp -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/X11R6/lib -L/usr/lib -L/usr/lib -lQGLViewer -lGLU -lGL -lQtXml -lQtOpenGL -L/usr/X11R6/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = window.cpp \
		glviewer.cpp \
		vertex.cpp \
		triangle.cpp \
		mesh.cpp \
		Main.cpp \
		glcolor.cpp .moc/moc_window.cpp \
		.moc/moc_glviewer.cpp
OBJECTS       = .obj/window.o \
		.obj/glviewer.o \
		.obj/vertex.o \
		.obj/triangle.o \
		.obj/mesh.o \
		.obj/Main.o \
		.obj/glcolor.o \
		.obj/moc_window.o \
		.obj/moc_glviewer.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		gm_open.pro
QMAKE_TARGET  = gm_open
DESTDIR       = 
TARGET        = gm_open

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gm_open.pro  /usr/share/qt4/mkspecs/default/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQGLViewer.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtCore.prl \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl
	$(QMAKE) -o Makefile gm_open.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQGLViewer.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtCore.prl:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile gm_open.pro

dist: 
	@$(CHK_DIR_EXISTS) .obj/gm_open1.0.0 || $(MKDIR) .obj/gm_open1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/gm_open1.0.0/ && $(COPY_FILE) --parents window.h glviewer.h vec3D.h vertex.h triangle.h mesh.h glcolor.h .obj/gm_open1.0.0/ && $(COPY_FILE) --parents window.cpp glviewer.cpp vertex.cpp triangle.cpp mesh.cpp Main.cpp glcolor.cpp .obj/gm_open1.0.0/ && (cd `dirname .obj/gm_open1.0.0` && $(TAR) gm_open1.0.0.tar gm_open1.0.0 && $(COMPRESS) gm_open1.0.0.tar) && $(MOVE) `dirname .obj/gm_open1.0.0`/gm_open1.0.0.tar.gz . && $(DEL_FILE) -r .obj/gm_open1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .moc/moc_window.cpp .moc/moc_glviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_window.cpp .moc/moc_glviewer.cpp
.moc/moc_window.cpp: glviewer.h \
		/usr/include/QGLViewer/qglviewer.h \
		/usr/include/QGLViewer/camera.h \
		/usr/include/QGLViewer/manipulatedCameraFrame.h \
		/usr/include/QGLViewer/manipulatedFrame.h \
		/usr/include/QGLViewer/frame.h \
		/usr/include/QGLViewer/constraint.h \
		/usr/include/QGLViewer/vec.h \
		/usr/include/math.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/huge_val.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/huge_valf.h \
		/usr/include/bits/huge_vall.h \
		/usr/include/bits/inf.h \
		/usr/include/bits/nan.h \
		/usr/include/bits/mathdef.h \
		/usr/include/bits/mathcalls.h \
		/usr/include/bits/mathinline.h \
		/usr/include/QGLViewer/config.h \
		/usr/include/GL/glut.h \
		/usr/include/GL/freeglut_std.h \
		/usr/include/GL/gl.h \
		/usr/include/GL/gl_mangle.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/xlocale.h \
		/usr/include/sys/types.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/GL/mesa_wgl.h \
		/usr/include/GL/glext.h \
		/usr/include/inttypes.h \
		/usr/include/stdint.h \
		/usr/include/bits/wchar.h \
		/usr/include/GL/glu.h \
		/usr/include/GL/glu_mangle.h \
		/usr/include/QGLViewer/quaternion.h \
		/usr/include/QGLViewer/mouseGrabber.h \
		/usr/include/QGLViewer/keyFrameInterpolator.h \
		mesh.h \
		vertex.h \
		vec3D.h \
		triangle.h \
		edge.h \
		window.h
	/usr/bin/moc $(DEFINES) $(INCPATH) window.h -o .moc/moc_window.cpp

.moc/moc_glviewer.cpp: /usr/include/QGLViewer/qglviewer.h \
		/usr/include/QGLViewer/camera.h \
		/usr/include/QGLViewer/manipulatedCameraFrame.h \
		/usr/include/QGLViewer/manipulatedFrame.h \
		/usr/include/QGLViewer/frame.h \
		/usr/include/QGLViewer/constraint.h \
		/usr/include/QGLViewer/vec.h \
		/usr/include/math.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/huge_val.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/huge_valf.h \
		/usr/include/bits/huge_vall.h \
		/usr/include/bits/inf.h \
		/usr/include/bits/nan.h \
		/usr/include/bits/mathdef.h \
		/usr/include/bits/mathcalls.h \
		/usr/include/bits/mathinline.h \
		/usr/include/QGLViewer/config.h \
		/usr/include/GL/glut.h \
		/usr/include/GL/freeglut_std.h \
		/usr/include/GL/gl.h \
		/usr/include/GL/gl_mangle.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/xlocale.h \
		/usr/include/sys/types.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/GL/mesa_wgl.h \
		/usr/include/GL/glext.h \
		/usr/include/inttypes.h \
		/usr/include/stdint.h \
		/usr/include/bits/wchar.h \
		/usr/include/GL/glu.h \
		/usr/include/GL/glu_mangle.h \
		/usr/include/QGLViewer/quaternion.h \
		/usr/include/QGLViewer/mouseGrabber.h \
		/usr/include/QGLViewer/keyFrameInterpolator.h \
		mesh.h \
		vertex.h \
		vec3D.h \
		triangle.h \
		edge.h \
		glviewer.h
	/usr/bin/moc $(DEFINES) $(INCPATH) glviewer.h -o .moc/moc_glviewer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

.obj/window.o: window.cpp window.h \
		glviewer.h \
		/usr/include/QGLViewer/qglviewer.h \
		/usr/include/QGLViewer/camera.h \
		/usr/include/QGLViewer/manipulatedCameraFrame.h \
		/usr/include/QGLViewer/manipulatedFrame.h \
		/usr/include/QGLViewer/frame.h \
		/usr/include/QGLViewer/constraint.h \
		/usr/include/QGLViewer/vec.h \
		/usr/include/math.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/huge_val.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/huge_valf.h \
		/usr/include/bits/huge_vall.h \
		/usr/include/bits/inf.h \
		/usr/include/bits/nan.h \
		/usr/include/bits/mathdef.h \
		/usr/include/bits/mathcalls.h \
		/usr/include/bits/mathinline.h \
		/usr/include/QGLViewer/config.h \
		/usr/include/GL/glut.h \
		/usr/include/GL/freeglut_std.h \
		/usr/include/GL/gl.h \
		/usr/include/GL/gl_mangle.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/xlocale.h \
		/usr/include/sys/types.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/GL/mesa_wgl.h \
		/usr/include/GL/glext.h \
		/usr/include/inttypes.h \
		/usr/include/stdint.h \
		/usr/include/bits/wchar.h \
		/usr/include/GL/glu.h \
		/usr/include/GL/glu_mangle.h \
		/usr/include/QGLViewer/quaternion.h \
		/usr/include/QGLViewer/mouseGrabber.h \
		/usr/include/QGLViewer/keyFrameInterpolator.h \
		mesh.h \
		vertex.h \
		vec3D.h \
		triangle.h \
		edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/window.o window.cpp

.obj/glviewer.o: glviewer.cpp glviewer.h \
		/usr/include/QGLViewer/qglviewer.h \
		/usr/include/QGLViewer/camera.h \
		/usr/include/QGLViewer/manipulatedCameraFrame.h \
		/usr/include/QGLViewer/manipulatedFrame.h \
		/usr/include/QGLViewer/frame.h \
		/usr/include/QGLViewer/constraint.h \
		/usr/include/QGLViewer/vec.h \
		/usr/include/math.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/huge_val.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/huge_valf.h \
		/usr/include/bits/huge_vall.h \
		/usr/include/bits/inf.h \
		/usr/include/bits/nan.h \
		/usr/include/bits/mathdef.h \
		/usr/include/bits/mathcalls.h \
		/usr/include/bits/mathinline.h \
		/usr/include/QGLViewer/config.h \
		/usr/include/GL/glut.h \
		/usr/include/GL/freeglut_std.h \
		/usr/include/GL/gl.h \
		/usr/include/GL/gl_mangle.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/xlocale.h \
		/usr/include/sys/types.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/GL/mesa_wgl.h \
		/usr/include/GL/glext.h \
		/usr/include/inttypes.h \
		/usr/include/stdint.h \
		/usr/include/bits/wchar.h \
		/usr/include/GL/glu.h \
		/usr/include/GL/glu_mangle.h \
		/usr/include/QGLViewer/quaternion.h \
		/usr/include/QGLViewer/mouseGrabber.h \
		/usr/include/QGLViewer/keyFrameInterpolator.h \
		mesh.h \
		vertex.h \
		vec3D.h \
		triangle.h \
		edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/glviewer.o glviewer.cpp

.obj/vertex.o: vertex.cpp vertex.h \
		/usr/include/QGLViewer/qglviewer.h \
		/usr/include/QGLViewer/camera.h \
		/usr/include/QGLViewer/manipulatedCameraFrame.h \
		/usr/include/QGLViewer/manipulatedFrame.h \
		/usr/include/QGLViewer/frame.h \
		/usr/include/QGLViewer/constraint.h \
		/usr/include/QGLViewer/vec.h \
		/usr/include/math.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/huge_val.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/huge_valf.h \
		/usr/include/bits/huge_vall.h \
		/usr/include/bits/inf.h \
		/usr/include/bits/nan.h \
		/usr/include/bits/mathdef.h \
		/usr/include/bits/mathcalls.h \
		/usr/include/bits/mathinline.h \
		/usr/include/QGLViewer/config.h \
		/usr/include/GL/glut.h \
		/usr/include/GL/freeglut_std.h \
		/usr/include/GL/gl.h \
		/usr/include/GL/gl_mangle.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/xlocale.h \
		/usr/include/sys/types.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/GL/mesa_wgl.h \
		/usr/include/GL/glext.h \
		/usr/include/inttypes.h \
		/usr/include/stdint.h \
		/usr/include/bits/wchar.h \
		/usr/include/GL/glu.h \
		/usr/include/GL/glu_mangle.h \
		/usr/include/QGLViewer/quaternion.h \
		/usr/include/QGLViewer/mouseGrabber.h \
		/usr/include/QGLViewer/keyFrameInterpolator.h \
		vec3D.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/vertex.o vertex.cpp

.obj/triangle.o: triangle.cpp triangle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/triangle.o triangle.cpp

.obj/mesh.o: mesh.cpp mesh.h \
		/usr/include/GL/glut.h \
		/usr/include/GL/freeglut_std.h \
		/usr/include/GL/gl.h \
		/usr/include/GL/gl_mangle.h \
		/usr/include/stdlib.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/xlocale.h \
		/usr/include/sys/types.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/GL/mesa_wgl.h \
		/usr/include/GL/glext.h \
		/usr/include/inttypes.h \
		/usr/include/stdint.h \
		/usr/include/bits/wchar.h \
		/usr/include/GL/glu.h \
		/usr/include/GL/glu_mangle.h \
		vertex.h \
		/usr/include/QGLViewer/qglviewer.h \
		/usr/include/QGLViewer/camera.h \
		/usr/include/QGLViewer/manipulatedCameraFrame.h \
		/usr/include/QGLViewer/manipulatedFrame.h \
		/usr/include/QGLViewer/frame.h \
		/usr/include/QGLViewer/constraint.h \
		/usr/include/QGLViewer/vec.h \
		/usr/include/math.h \
		/usr/include/bits/huge_val.h \
		/usr/include/bits/huge_valf.h \
		/usr/include/bits/huge_vall.h \
		/usr/include/bits/inf.h \
		/usr/include/bits/nan.h \
		/usr/include/bits/mathdef.h \
		/usr/include/bits/mathcalls.h \
		/usr/include/bits/mathinline.h \
		/usr/include/QGLViewer/config.h \
		/usr/include/QGLViewer/quaternion.h \
		/usr/include/QGLViewer/mouseGrabber.h \
		/usr/include/QGLViewer/keyFrameInterpolator.h \
		vec3D.h \
		triangle.h \
		edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mesh.o mesh.cpp

.obj/Main.o: Main.cpp window.h \
		glviewer.h \
		/usr/include/QGLViewer/qglviewer.h \
		/usr/include/QGLViewer/camera.h \
		/usr/include/QGLViewer/manipulatedCameraFrame.h \
		/usr/include/QGLViewer/manipulatedFrame.h \
		/usr/include/QGLViewer/frame.h \
		/usr/include/QGLViewer/constraint.h \
		/usr/include/QGLViewer/vec.h \
		/usr/include/math.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/huge_val.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/huge_valf.h \
		/usr/include/bits/huge_vall.h \
		/usr/include/bits/inf.h \
		/usr/include/bits/nan.h \
		/usr/include/bits/mathdef.h \
		/usr/include/bits/mathcalls.h \
		/usr/include/bits/mathinline.h \
		/usr/include/QGLViewer/config.h \
		/usr/include/GL/glut.h \
		/usr/include/GL/freeglut_std.h \
		/usr/include/GL/gl.h \
		/usr/include/GL/gl_mangle.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/xlocale.h \
		/usr/include/sys/types.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/GL/mesa_wgl.h \
		/usr/include/GL/glext.h \
		/usr/include/inttypes.h \
		/usr/include/stdint.h \
		/usr/include/bits/wchar.h \
		/usr/include/GL/glu.h \
		/usr/include/GL/glu_mangle.h \
		/usr/include/QGLViewer/quaternion.h \
		/usr/include/QGLViewer/mouseGrabber.h \
		/usr/include/QGLViewer/keyFrameInterpolator.h \
		mesh.h \
		vertex.h \
		vec3D.h \
		triangle.h \
		edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Main.o Main.cpp

.obj/glcolor.o: glcolor.cpp glcolor.h \
		/usr/include/QGLViewer/qglviewer.h \
		/usr/include/QGLViewer/camera.h \
		/usr/include/QGLViewer/manipulatedCameraFrame.h \
		/usr/include/QGLViewer/manipulatedFrame.h \
		/usr/include/QGLViewer/frame.h \
		/usr/include/QGLViewer/constraint.h \
		/usr/include/QGLViewer/vec.h \
		/usr/include/math.h \
		/usr/include/features.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/huge_val.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/huge_valf.h \
		/usr/include/bits/huge_vall.h \
		/usr/include/bits/inf.h \
		/usr/include/bits/nan.h \
		/usr/include/bits/mathdef.h \
		/usr/include/bits/mathcalls.h \
		/usr/include/bits/mathinline.h \
		/usr/include/QGLViewer/config.h \
		/usr/include/GL/glut.h \
		/usr/include/GL/freeglut_std.h \
		/usr/include/GL/gl.h \
		/usr/include/GL/gl_mangle.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/xlocale.h \
		/usr/include/sys/types.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/GL/mesa_wgl.h \
		/usr/include/GL/glext.h \
		/usr/include/inttypes.h \
		/usr/include/stdint.h \
		/usr/include/bits/wchar.h \
		/usr/include/GL/glu.h \
		/usr/include/GL/glu_mangle.h \
		/usr/include/QGLViewer/quaternion.h \
		/usr/include/QGLViewer/mouseGrabber.h \
		/usr/include/QGLViewer/keyFrameInterpolator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/glcolor.o glcolor.cpp

.obj/moc_window.o: .moc/moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_window.o .moc/moc_window.cpp

.obj/moc_glviewer.o: .moc/moc_glviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_glviewer.o .moc/moc_glviewer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

